@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Sep 26 19:07:13 +0800 2018
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim ElevatorFile_TB_behav -key {Behavioral:sim_1:Functional:ElevatorFile_TB} -tclbatch ElevatorFile_TB.tcl -view C:/Users/smdsbz/Projects/WasherController/Simulations/TopModule_TB_behav.wcfg -view C:/Users/smdsbz/Projects/WasherController/Simulations/TopModule_Bug_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
